### ISSUE TITLE
[BUG] 'UnityFileHelper' does not contain a definition for 'GetAllFilesAtPath'

### ISSUE THREAD

**Issue by FejZa** [realitycollective/com.realitycollective.service-framework#55]
After updating to latest SF release I get this error in the console:

`
Library\PackageCache\com.realitycollective.service-framework@1.0.3-pre.4\Editor\Packages\AssetsInstaller.cs(84,66): error CS0117: 'UnityFileHelper' does not contain a definition for 'GetAllFilesAtPath'
`

**Comment by SimonDarksideJ** [comment]
That's because you need to update your utilities package too @din0m1te

**Comment by FejZa** [comment]
That should happen implicitly. Looks like you did not bump the dependency in the manifest.

**Comment by SimonDarksideJ** [comment]
You are quite right, I shall fix that now

**Comment by SimonDarksideJ** [comment]
Resolved with https://github.com/realitycollective/com.realitycollective.service-framework/pull/56
