### ISSUE TITLE
The Service Framework should support the Dependency Injection pattern of defining Interfaces as dependencies

### ISSUE THREAD

**Issue by SimonDarksideJ** [realitycollective/com.realitycollective.service-framework#58]
# Reality Collective - Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

The Dependency Injection Pattern defines a method where at design time, the developer can define the interfaces that a service needs in order to properly instantiate
https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection

This controls the order in which services instantiate and enable tighter "loosely coupled" integration between services and ensures a dependent service is available to wire up events when a service starts.

## How would you classify your suggestion

- Architecture / Services

## Describe the solution you'd like

The ability to define service interface dependencies in the design of a service and have the service framework automatically recognise the dependency on startup.

## Describe alternatives you've considered

Manual

## Migrated from
https://github.com/realitycollective/realitytoolkit.dev/issues/64

**Comment by SimonDarksideJ** [comment]
@FejZa could you list some simple examples / use-cases to test with while building out this feature?

**Comment by FejZa** [comment]
Not entirely sure, what you mean. But I imagine it to work like this, once it works:

`MyTestServiceModule(IInputService inputService, ILocomotionService locomotionService) {}`

and then those dependencies are injected with the currently active implementation of the interface.

**Comment by SimonDarksideJ** [comment]
Duplicate of #84 which has more detail
