### ISSUE TITLE
Make service profile type optional

### ISSUE THREAD

**Issue by LocalJoost** [realitycollective/com.realitycollective.service-framework#63]
# Reality Collective - Service Framework Feature Request

A service framework _must_ have a profile even if it doesn't need one. 

Exhibit A:

![image](https://github.com/realitycollective/com.realitycollective.service-framework/assets/4129183/1c96ba1a-7dc2-4f24-8161-ab819a33ae3d)

If I remove the profile from the constructor:

![image](https://github.com/realitycollective/com.realitycollective.service-framework/assets/4129183/7ddbe68d-4bd8-41d9-9242-f7f633f16575)

It disappears nicely from the UI:

![image](https://github.com/realitycollective/com.realitycollective.service-framework/assets/4129183/6f9507f8-22f9-49e9-9b70-9c313be1b813)

But then unfortunately an error pops up in Unity:

**Failed to register the MRTK3ConfigurationFindingService service: System.MissingMethodException - Constructor on type 'MRTKExtensions.Services.MRTK3ConfigurationFindingService' not found.**

Not sure if this is a feature request or a bug, but I thought to leave here as a feature request anyway.

Using Service Framework version 1.0.3 and Utilities 1.0.5

**Comment by SimonDarksideJ** [comment]
If you do not want a profile, then set the profile type to "BaseProfile" and it will not be expected.

This is the default if you leave the checkbox for "profile required" unchecked when you generate the service.

**Comment by LocalJoost** [comment]
I *really* have a hard time believing I actually missed spotting this rather obvious checkbox. Never mind...
![image](https://github.com/realitycollective/com.realitycollective.service-framework/assets/4129183/6d3cefa1-f2e3-469f-9c00-cd137fd0523a)

**Comment by SimonDarksideJ** [comment]
FUnnier is that by DEFAULT this box is unchecked :D , so you have to choose to check it :P
