### ISSUE TITLE
Introduce service containers

### ISSUE THREAD

**Issue by FejZa** [realitycollective/com.realitycollective.service-framework#64]
# Reality Collective - Service Framework Feature Request

## Is your feature request related to a problem? Please describe

At this time, the service framework is essentially one global container of services. What I am suggesting instead is extending it in a way that allows multiple service containers, that are created / destroyed as needed.

Common usage scenario:

- Base Scene: Contains the main service container and persists across scenes
- SceneA: Contains a service container with services only relevant to SceneA. Once SceneA is unloaded, all of the services in the container are destroyed and unregistered from the service manager

The current setup introduces issues when services are not meant to persist across scenes or meant to not exist at all, if a certain is not loaded. A lot of overhead code is required, to reset those services to an idle/reset state, as scenes are loaded/unloaded.

**Comment by SimonDarksideJ** [comment]
So, the request is progressing. What is done so far:

* Added a new scriptable object configuration to define services for a scene. (Scene service config)
* Added configuration and a property draw to assign and show the "scene" service configurations.
* Enabled loading of services for scenes on Start and loading of new scenes (the easy part) 

ToDo
* the slightly more complicated task of unloading services using the service config
