### ISSUE TITLE
Add support for service interface inheritance

### ISSUE THREAD

**Issue by FejZa** [realitycollective/com.realitycollective.service-framework#73]
# Reality Collective - Service Framework Feature Request

## Is your feature request related to a problem? Please describe

So this is sorts of an edge case issue and there is many ways to work around it. But maybe something easy enough to fix.

Image the following scenario:

- A user is using the Reality Toolkit
- They create a custom input service definition `IMyInputService` that is defined as `public interface IMyInputService : IInputService`
- Then they create an implementation of that service and register it
- Now all Reality Toolkit services that depend on `IInputService` will still fail to look it up because `IMyInputService` is not identified as a valid `IInputService`

**Comment by SimonDarksideJ** [comment]
Completed as of https://github.com/realitycollective/com.realitycollective.service-framework/pull/110
