### ISSUE TITLE
Service / Module wizard should prefill with root namespace instead pf product name for the namespace

### ISSUE THREAD

**Issue by FejZa** [realitycollective/com.realitycollective.service-framework#88]
# Reality Collective - Service Framework Feature Request

## Is your feature request related to a problem? Please describe

![image](https://github.com/realitycollective/com.realitycollective.service-framework/assets/9565734/2f20d0f9-0e91-4c99-a4c4-a10509abccdb)

When generating a service / module the wizard will prefill with the product name in the namespace field. It should rather use the root namespace configured in the project settings and only fallback to product name, if none configured.

![image](https://github.com/realitycollective/com.realitycollective.service-framework/assets/9565734/3a3045b2-fcbd-4518-9a74-16627528c731)

**Comment by SimonDarksideJ** [comment]
Updated to use RootNamespace if configured, defaults to the current setup if not configured.

**Comment by FejZa** [comment]
Fixed.
