### ISSUE TITLE
Root ServiceProvidersProfile should not list Modules for selection

### ISSUE THREAD

**Issue by FejZa** [realitycollective/com.realitycollective.service-framework#89]
# Reality Collective - Service Framework Bug Report

## Describe the bug

When registering services with the root profile it lists literally anything that is an `IService`. This dropdown should filter `IServiceModule` types and not list them as it does not make sense to register a module at root level.

**Comment by SimonDarksideJ** [comment]
This is a known issue, as the drop-down filters all classes implementing "IService" which also includes "IServiceModules", have not found a good workaround that does not break the filtering of "IServiceModules" for modules too.

Will have a look again.

**Comment by FejZa** [comment]
Fixed.
