### ISSUE TITLE
Service (module) wizard remembers last used generation path even from other projects

### ISSUE THREAD

**Issue by FejZa** [realitycollective/com.realitycollective.service-framework#90]
# Reality Collective - Service Framework Bug Report

## Describe the bug

The service wizard now remembers the last used path to generated services at, which is great. Unfortunately
this is true even across projects. So when I work in Unity project A and generated a service. Then move on to project B, the wizard will suggest generating at a path within project A.

**Comment by SimonDarksideJ** [comment]
Say it isn't so....  I shall send in the troops.
