### ISSUE TITLE
There is no way to know whether scene services have initialized

### ISSUE THREAD

**Issue by FejZa** [realitycollective/com.realitycollective.service-framework#95]
# Reality Collective - Service Framework Feature Request

## Is your feature request related to a problem? Please describe

When working with the new scene services features, there is no way to know whether the scene service container has initialized. ServiceManager.WaitUntilInitializedAsync() should be updated to consider scene services as well.

**Comment by FejZa** [comment]
I have implemented this. PR is coming.

**Comment by SimonDarksideJ** [comment]
Completed
